# gitleaks configuration file
# https://github.com/gitleaks/gitleaks

[allowlist]
    description = "Global allowlist"
    paths = [
        "vendor",
        "runtime",
        "composer.lock",
        ".git"
    ]
    regexes = [
        "test_.*",
        "example_.*"
    ]
